Repository infinispan/infinispan-console, pull requests merged in 2021-01, with the labels that each got.

#107 ISPN-12610 Protobuf data manipulation fix
  src/__tests__/services/utils.test.ts
  src/app/Caches/Entries/CacheEntries.tsx
  src/services/cacheService.ts
  src/services/utils.ts
Labels: bug

#109 ISPN-12613 Upgrade patternfly to release 2020.16
  package.json
Labels: Trivial :)

#113 ISPN-12640 Deal with server error in getEntries
  src/app/providers/CacheDetailProvider.tsx
  src/services/cacheService.ts
  src/services/utils.ts
Labels: Trivial :), bug

#114 ISPN-12654 Fix getentry for protobuf caches
  src/app/Caches/Entries/CacheEntries.tsx
Labels: Trivial :), bug

#116 ISPN-12660 skipTests property for local build
  README.md
  pom.xml
Labels: Trivial :)

#118 [11.0.x] ISPN-12661 Licenses are not properly generated
  pom.xml
  src/main/resources/licenses/build.xml
Labels: backport
