Repository infinispan/infinispan-console, pull requests merged in 2022-11, with the labels that each got.

#277 ISPN-14271 Cache wizard back button not working
  src/app/Caches/Create/CreateCacheWizard.tsx
Labels: bug

#278 ISPN-14264 Counters page - double click on Strong/Weak sele…
  data/create-data.sh
  scripts/infinispan-basic-auth.xml
  src/app/CacheManagers/CounterTableDisplay.tsx
Labels: bug

#279 ISPN-14264 Counters page - double click on Strong/Weak select loads a…
  data/create-data.sh
  scripts/infinispan-basic-auth.xml
  src/app/CacheManagers/CounterTableDisplay.tsx
Labels: bug, backport

#290 [14.x] ISPN-14322 Default number of owners is 2
  src/app/providers/CreateCacheProvider.tsx
Labels: backport

#291 [14.x] ISPN-14246 Query metrics tooltip refactoring
  src/app/Caches/Query/QueryMetrics.tsx
  src/app/assets/languages/en.json
Labels: backport
