Repository infinispan/infinispan-console, pull requests merged in 2022-12, with the labels that each got.

#288 ISPN-14354 Backups disabled even when the cluster is cross site
  src/app/Caches/Create/Features/BackupsCacheConfigurator.tsx
  src/app/assets/languages/en.json
  src/services/dataContainerService.ts
Labels: Trivial :)

#289 [14.x] ISPN-14354 Backups disabled even when the cluster is cross site
  src/app/Caches/Create/Features/BackupsCacheConfigurator.tsx
  src/app/assets/languages/en.json
  src/services/dataContainerService.ts
Labels: backport

#298 ISPN-14266 Cache creation wizard: it is still possible to create inde…
  package-lock.json
  src/app/Caches/Create/BasicCacheConfigConfigurator.tsx
  src/app/Caches/Create/Features/IndexedCacheConfigurator.tsx
  src/app/utils/featuresValidation.ts
Labels: bug

#303 ISPN-14417 The metrics for misses and retrievals are updated after page reload
  src/app/Caches/DetailCache.tsx
Labels: bug
